name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Subrat-IO
          output: dist/github-contribution-grid-snake.svg
      
      - name: Push snake.svg to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          folder: dist
          commit_message: "Update snake animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
